CREATE TABLE [dbo].[Teams]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    [Number] INT NOT NULL IDENTITY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Sport] NVARCHAR(50) NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [PK_Teams] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Teams_Users] FOREIGN KEY (UserId) REFERENCES Users(Id) 
)
